version: "3.9"  # optional since v1.27.0

services:
    app:
        build:
          context: .
          dockerfile: Dockerfile
        image: app
        #container_name: web_application
        ports:
          - "8080:80"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        #container_name: sqlserver2022
        ports: # not actually needed, because the two services are on the same network
          - "1433:1433"

        environment:
          -  MSSQL_SA_PASSWORD=yourStrong(!)Password
          -  ACCEPT_EULA=Y
          -  MSSQL_PID=Express